package com.ddanss.airecipe.components

import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable



@Composable
fun HistoryScreen(contentPadding: PaddingValues) {
    LazyColumn {
        items(texts) { text ->
            Text(text)
        }
    }
}

// test array of texts.
val texts = listOf(
    "This is a sample text",
    "This is another sample text",
    "This is a third sample text",
    "This is a fourth sample text",
    "This is a fifth sample text",
    "This is a sixth sample text",
    "This is a seventh sample text",
    "This is a eighth sample text",
    "This is a ninth sample text",
    "This is a tenth sample text",
    "This is a eleventh sample text",
    "This is a twelfth sample text",
    "This is a thirteenth sample text",
    "This is a fourteenth sample text",
    "This is a fifteenth sample text",
    "This is a sixteenth sample text",
    "This is a seventeenth sample text",
    "This is a eighteenth sample text",
    "This is a nineteenth sample text",
    "This is a twentieth sample text",
    "This is a sample text",
    "This is another sample text",
    "This is a third sample text",
    "This is a fourth sample text",
    "This is a fifth sample text",
    "This is a sixth sample text",
    "This is a seventh sample text",
    "This is a eighth sample text",
    "This is a ninth sample text",
    "This is a tenth sample text",
    "This is a eleventh sample text",
    "This is a twelfth sample text",
    "This is a thirteenth sample text",
    "This is a fourteenth sample text",
    "This is a fifteenth sample text",
    "This is a sixteenth sample text",
    "This is a seventeenth sample text",
    "This is a eighteenth sample text",
    "This is a nineteenth sample text",
    "This is a twentieth sample text",
    "This is a sample text",
    "This is another sample text",
    "This is a third sample text",
    "This is a fourth sample text",
    "This is a fifth sample text",
    "This is a sixth sample text",
    "This is a seventh sample text",
    "This is a eighth sample text",
    "This is a ninth sample text",
    "This is a tenth sample text",
    "This is a eleventh sample text",
    "This is a twelfth sample text",
    "This is a thirteenth sample text",
    "This is a fourteenth sample text",
    "This is a fifteenth sample text",
    "This is a sixteenth sample text",
    "This is a seventeenth sample text",
    "This is a eighteenth sample text",
    "This is a nineteenth sample text",
    "This is a twentieth sample text",
    "This is a sample text",
    "This is another sample text",
    "This is a third sample text",
    "This is a fourth sample text",
    "This is a fifth sample text",
    "This is a sixth sample text",
    "This is a seventh sample text",
    "This is a eighth sample text",
    "This is a ninth sample text",
    "This is a tenth sample text",
    "This is a eleventh sample text",
    "This is a twelfth sample text",
    "This is a thirteenth sample text",
    "This is a fourteenth sample text",
    "This is a fifteenth sample text",
    "This is a sixteenth sample text",
    "This is a seventeenth sample text",
    "This is a eighteenth sample text",
    "This is a nineteenth sample text",
    "This is a twentieth sample text",
    "This is a sample text",
    "This is another sample text",
    "This is a third sample text",
    "This is a fourth sample text",
    "This is a fifth sample text",
    "This is a sixth sample text",
    "This is a seventh sample text",
    "This is a eighth sample text",
    "This is a ninth sample text",
    "This is a tenth sample text",
    "This is a eleventh sample text",
    "This is a twelfth sample text",
    "This is a thirteenth sample text",
    "This is a fourteenth sample text",
    "This is a fifteenth sample text",
    "This is a sixteenth sample text",
    "This is a seventeenth sample text",
    "This is a eighteenth sample text",
    "This is a nineteenth sample text",
    "This is a twentieth sample text",
    "This is a sample text",
    "This is another sample text",
    "This is a third sample text",
    "This is a fourth sample text",
    "This is a fifth sample text",
    "This is a sixth sample text",
    "This is a seventh sample text",
    "This is a eighth sample text",
    "This is a ninth sample text",
    "This is a tenth sample text",
    "This is a eleventh sample text",
    "This is a twelfth sample text",
    "This is a thirteenth sample text",
    "This is a fourteenth sample text",
    "This is a fifteenth sample text",
    "This is a sixteenth sample text",
    "This is a seventeenth sample text",
    "This is a eighteenth sample text",
    "This is a nineteenth sample text",
    "This is a twentieth sample text",
)